name = "grace-ahrens"
compatibility_date = "2024-06-01"
pages_build_output_dir = "."

[[kv_namespaces]]
binding = "ADMIN_KV"
id = "abd1b9b9f0e1468fb67d0f5d6d97eb29"

[[services]]
binding = "EMAIL_WORKER"
service = "grace-ahrens-email"
