name = "grace-ahrens-scheduler"
main = "src/index.js"
compatibility_date = "2024-06-01"
workers_dev = false

[[kv_namespaces]]
binding = "ADMIN_KV"
id = "abd1b9b9f0e1468fb67d0f5d6d97eb29"

[[services]]
binding = "EMAIL_WORKER"
service = "chess-accounts"

[triggers]
crons = ["0 * * * *"]
